{{ config(materialized='view', schema='bronze') }}

select
    id,
    symbol,
    name,
    current_price,
    market_cap,
    total_volume,
    high_24h,
    low_24h,
    price_change_24h,
    price_change_percentage_24h,
    market_cap_rank,
    fully_diluted_valuation,
    market_cap_change_24h,
    market_cap_change_percentage_24h,
    circulating_supply,
    total_supply,
    max_supply,
    ath,
    ath_change_percentage,
    ath_date,
    atl,
    atl_change_percentage,
    atl_date,
    volume_to_market_cap_ratio,
    last_updated,
    ingestion_ts,
    source,
    run_key
from {{ source('bronze', 'coingecko_market_data') }}
